[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = '''
delay(0.4); ease_ante(1); delay(0.4); check_for_unlock({type = 'ante_up', ante = G.GAME.round_resets.ante + 1})
'''
position = "after"
payload = '''
for i=G.TerraPotion.Temp_luck_increase / 2, 0, -1 do
    for k, v in pairs(G.GAME.probabilities) do 
        G.GAME.probabilities[k] = v/2
    end
end
G.TerraPotion.Temp_luck_increase = 0
'''
match_indent = true
overwrite = false