[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = "game.lua"
pattern = '''
        G.shop_booster:emplace(card)
    end
end
'''
position = "after"
payload = '''
SMODS.change_booster_limit(-G.TerraPotion.Temp_booster_increase)
G.TerraPotion.Temp_booster_increase = 0
'''
match_indent = true
overwrite = false


[[patches]]
[patches.pattern]
target = "game.lua"
pattern = '''
remove_all(G.STAGE_OBJECTS[G.STAGE])
'''
position = "after"
payload = '''
G.TerraPotion.Temp_booster_increase = 0
'''
match_indent = true
overwrite = false