[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

#custom tag contexts
#before
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = '''
mult, hand_chips = mod_mult(mult), mod_chips(hand_chips)
'''
position = "after"
payload = '''
for i = 1, #G.GAME.tags do
    G.GAME.tags[i]:apply_to_run({type = 'before'})
end
'''
match_indent = true
overwrite = false

#after
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = '''
SMODS.calculate_context({full_hand = G.play.cards, scoring_hand = scoring_hand, scoring_name = text, poker_hands = poker_hands, final_scoring_step = true})
'''
position = "before"
payload = '''
for i = 1, #G.GAME.tags do
    G.GAME.tags[i]:apply_to_run({type = 'after'})
end
'''
match_indent = true
overwrite = false

#skip_blind
[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
pattern = '''
            if G.GAME.tags[i]:apply_to_run({type = 'new_blind_choice'}) then break end
          end
          return true
        end
      }))
    end
'''
position = "after"
payload = '''
for i = 1, #G.GAME.tags do
    G.GAME.tags[i]:apply_to_run({type = 'skip_blind'})
end
G.TerraPotion.ReturnTagTrigger = false
'''
match_indent = true
overwrite = false